version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: go-postgres
    environment:
      POSTGRES_USER: go-boilerplate
      POSTGRES_PASSWORD: go-boilerplate
      POSTGRES_DB: go-boilerplate-db
    ports:
      - "5443:5432"
    volumes:
      - go_postgres_data:/var/lib/postgresql/data

volumes:
  go_postgres_data: